version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile_elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=${NODE_TYPE}
      - ES_JAVA_OPTS=${ES_OPTS}
      - xpack.security.enabled=${SECURITY_CONFIG}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ELASTICSEARCH_PLUGINS=${ES_PLUGIN}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "${ES_INTERNAL_PORT_1}:${ES_EXTERNAL_PORT_1}"
      - "${ES_INTERNAL_PORT_2}:${ES_EXTERNAL_PORT_2}"
    networks:
      - LLL3_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  kibana:
    image: kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_INTERNAL_PORT}:${KIBANA_EXTERNAL_PORT}"
    networks:
      - LLL3_network
    environment:
      ELASTICSEARCH_HOSTS: "http://${ES_HOST}:${ES_EXTERNAL_PORT_1}"

  mysql:
    image: mysql:8.0
    #    restart: always
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_INTERNAL_PORT}:${REDIS_EXTERNAL_PORT}"
    networks:
      - LLL3_network

networks:
  LLL3_network:
    driver: bridge