version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile_elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=${NODE_TYPE}
      - ES_JAVA_OPTS=${ES_OPTS}
      - xpack.security.enabled=${SECURITY_CONFIG}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ELASTICSEARCH_PLUGINS=${ES_PLUGIN}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - LLL3_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  kibana:
    image: kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - LLL3_network
    environment:
      ELASTICSEARCH_HOSTS: ${ES_HOST}

  mysql:
    image: mysql:8.0
    #    restart: always
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - LLL3_network

networks:
  LLL3_network:
    driver: bridge