spring:
  application:
    name: sangchu

  profiles:
    active: ${PROFILE}

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
  data:
    redis:
      port: ${REDIS_EXTERNAL_PORT}

  elasticsearch:
    limit: ${ES_LIMIT}
    index-name: ${INDEX_NAME}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-4-turbo
          temperature: 1

springdoc:
  swagger-ui:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

kipris:
  service-key: ${KIPRIS_SERVICE_KEY}
  request-url: ${KIPRIS_REQUEST_URL}

# =========================== LOCAL  ===========================
---
spring.config.activate.on-profile: local

server:
  port: ${LOCAL_SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${LOCAL_HOST}:${MYSQL_EXTERNAL_PORT}/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  data:
    redis:
      host: ${LOCAL_HOST}

  elasticsearch:
    uris: http://${LOCAL_HOST}:${ES_EXTERNAL_PORT_1}/
    connection-timeout: 600s
    socket-timeout: 600s

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: false

embed:
  huggingface:
    uri: ${LOCAL_HUGGINGFACE_URI}

# 디버깅 용도
logging-level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.data.elasticsearch.client: debug

# info:
#   web:
#     frontUrl: "http://localhost:8080"
#     domain: "localhost"

# =======================================  MAIN  =======================================
---
spring.config.activate.on-profile: main

server:
  port: ${MAIN_SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${MAIN_HOST}:${MYSQL_EXTERNAL_PORT}/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8

  data:
    redis:
      host: ${MAIN_HOST}

  elasticsearch:
    uris: http://${MAIN_HOST}:${ES_EXTERNAL_PORT_1}/
    connection-timeout: 600s
    socket-timeout: 600s

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false

embed:
  huggingface:
    uri: ${MAIN_HUGGINGFACE_URI}


# info:
#   web:
#     frontUrl: ""
#     domain: ""

---