version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: dockerfile_elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=${NODE_TYPE}
      - ES_JAVA_OPTS=${ES_OPTS}
      - xpack.security.enabled=${SECURITY_CONFIG}
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ELASTICSEARCH_PLUGINS=${ES_PLUGIN}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "${ES_INTERNAL_PORT_1}:${ES_EXTERNAL_PORT_1}"
      - "${ES_INTERNAL_PORT_2}:${ES_EXTERNAL_PORT_2}"
    networks:
      - LLL3_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_INTERNAL_PORT}:${KIBANA_EXTERNAL_PORT}"
    networks:
      - LLL3_network
    environment:
      ELASTICSEARCH_HOSTS: "http://${ES_HOST}:${ES_EXTERNAL_PORT_1}"
    env_file:
      - .env

  mysql:
    image: mysql:latest
    #    restart: always
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_INTERNAL_PORT}:${REDIS_EXTERNAL_PORT}"
    networks:
      - LLL3_network
    env_file:
      - .env

  backend:
    build:
      context: ../..
      dockerfile: infra/local/dockerfile_backend
    container_name: SANGCHU
    env_file:
      - .env
    ports:
      - "8080:8081"
    depends_on:
      - mysql
    networks:
      - LLL3_network
    restart: always

  frontend:
    build:
      context: ../../../LLL3_FRONTEND
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - LLL3_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - LLL3_network
    restart: always
    env_file:
      - .env

  embedding:
    build:
      context: .
      dockerfile: dockerfile_embedding
    container_name: embedding
    ports:
      - "5050:5050"
    networks:
      - LLL3_network
    restart: always

networks:
  LLL3_network:
    driver: bridge