# 1단계: 빌드 스테이지
FROM gradle:8.7-jdk21 AS builder

# 필요한 소스코드 전체 복사
WORKDIR /build
COPY . .

# Gradle로 jar 빌드 (bootJar task)
RUN gradle bootJar --no-daemon

# 2단계: 실행 스테이지
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y wget gnupg2

RUN apt-get update && apt-get install -y locales \
 && locale-gen ko_KR.UTF-8 \
 && update-locale LANG=ko_KR.UTF-8

ENV LANG=ko_KR.UTF-8
ENV LANGUAGE=ko_KR:ko
ENV LC_ALL=ko_KR.UTF-8

RUN wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - \
    && echo "deb https://packages.adoptium.net/artifactory/deb focal main" | tee /etc/apt/sources.list.d/adoptium.list \
    && apt-get update \
    && apt-get install -y temurin-21-jdk

RUN apt-get install -y \
    vim dos2unix curl \
    libglib2.0-0 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 \
    libxcb1 libxkbcommon0 libatspi2.0-0 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 \
    libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 빌드 스테이지에서 생성된 jar 파일 복사
COPY --from=builder /build/build/libs/*.jar app.jar

RUN chmod 777 /app/app.jar
ARG PROFILE
ENV PROFILE=${PROFILE}

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/app.jar"]